detect:
  log type: wel
  op: and
  rules:
  - op: and
    rules:
    - case sensitive: false
      op: is
      path: Event/System/EventID
      value: '13'
    - op: or
      rules:
      - case sensitive: false
        op: is
        path: Event/EventData/TargetObject
        value: HKLM\System\CurrentControlSet\Control\Lsa\Security Packages
      - case sensitive: false
        op: is
        path: Event/EventData/TargetObject
        value: HKLM\System\CurrentControlSet\Control\Lsa\OSConfig\Security Packages
  - not: true
    op: or
    rules:
    - case sensitive: false
      op: is
      path: Event/EventData/Image
      value: C:\Windows\system32\msiexec.exe
    - case sensitive: false
      op: is
      path: Event/EventData/Image
      value: C:\Windows\syswow64\MsiExec.exe
  target: log
respond:
- action: report
  metatdata:
    author: iwillkeepwatch
    description: Detects the addition of a SSP to the registry. Upon a reboot or API
      call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
    level: critical
    references:
    - https://attack.mitre.org/techniques/T1101/
    - https://powersploit.readthedocs.io/en/latest/Persistence/Install-SSP/
    tags:
    - attack.persistence
    - attack.t1011
  name: Security Support Provider (SSP) added to LSA configuration

