detect:
  log type: wel
  op: or
  rules:
  - case sensitive: false
    op: is
    path: Event/System/EventID
    value: '150'
  - case sensitive: false
    op: is
    path: Event/System/EventID
    value: '770'
  target: log
respond:
- action: report
  metatdata:
    author: Florian Roth
    description: This rule detects a DNS server error in which a specified plugin
      DLL (in registry) could not be loaded
    level: critical
    references:
    - https://medium.com/@esnesenon/feature-not-bug-dnsadmin-to-dc-compromise-in-one-line-a0f779b8dc83
    - https://technet.microsoft.com/en-us/library/cc735829(v=ws.10).aspx
    - https://twitter.com/gentilkiwi/status/861641945944391680
    tags:
    - attack.defense_evasion
    - attack.t1073
  name: DNS Server Error Failed Loading the ServerLevelPluginDLL

